# Generated by Django 3.2 on 2021-09-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('p_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=300)),
                ('p_description', models.CharField(max_length=1000)),
                ('p_price', models.IntegerField()),
                ('p_sort', models.CharField(max_length=300)),
                ('p_img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=300)),
                ('user_email', models.EmailField(max_length=300, unique=True)),
                ('user_password', models.CharField(max_length=300)),
            ],
        ),
    ]
