# Generated by Django 3.2 on 2021-09-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
