# Generated by Django 3.2 on 2021-09-05 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prods', '0003_auto_20210905_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='lux',
            fields=[
                ('pp_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('pp_name', models.CharField(max_length=300)),
                ('ppp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prods.products')),
            ],
        ),
    ]
