# Generated by Django 3.2 on 2021-09-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prods', '0011_alter_products_p_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_img',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
