# Generated by Django 3.2 on 2021-09-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prods', '0012_alter_products_p_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_img',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
