# Generated by Django 3.2 on 2021-09-09 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prods', '0013_alter_products_p_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('c_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='p_sort',
        ),
        migrations.AddField(
            model_name='products',
            name='p_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prods.category'),
        ),
    ]
