# Generated by Django 3.2 on 2021-09-09 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prods', '0014_auto_20210909_1517'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='categories',
        ),
    ]
