# Generated by Django 3.2 on 2021-09-10 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prods', '0015_rename_category_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lux',
        ),
    ]
