# Generated by Django 3.2 on 2021-09-24 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prods', '0016_delete_lux'),
    ]

    operations = [
        migrations.CreateModel(
            name='countries',
            fields=[
                ('countries_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('countries_name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='specialties',
            fields=[
                ('specialties_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('specialties_name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='regions',
            fields=[
                ('regions_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('regions_name', models.CharField(max_length=400)),
                ('regions_f_countries', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prods.countries')),
            ],
        ),
    ]
